### ISSUE TITLE
Chart 0.9.0 missing? (single)

### ISSUE THREAD

**Issue by tomislater** [timescale/helm-charts#299] opened 2021-07-14 12:23 UTC
I can only find `0.8.2` chart version. On [release page](https://github.com/timescale/timescaledb-kubernetes/releases) I see that the last release is from January, but [changelog](https://github.com/timescale/timescaledb-kubernetes/blob/master/CHANGELOG.md) says that there should be `0.9.0` version. In [helm repo](https://charts.timescale.com/index.yaml) I cannot find `0.9.0`.

I think, that it is also strange that `0.8.2` version was released on `2021-01-13`, but `0.9.0` "was released" on `2020-08-14` (in changelog). (`0.7.0` was also released on `2020-08-14`, so maybe it is just a copy&paste bug).

Nevertheless, it looks that `0.9.0` has not been released yet. It only exist on master. Is that okay? I ask because I want to deploy this chart, but I do not know which version should I use. I should just use the version from master branch or wait for the release on helm repo? Maybe someone just forgot to release `0.9.0` version?

**Comment by tomislater** [comment] 2021-07-15 11:25
Okay... I can add repo via `helm repo add timescaledb 'https://raw.githubusercontent.com/timescale/timescaledb-kubernetes/master/charts/repo/'` and it works, because there is a `0.9.0` version. So, maybe should I update documentation?

Looks that [helm repo](https://github.com/timescale/timescaledb-kubernetes/tree/master/charts/timescaledb-single#installing-from-the-timescale-helm-repo) has not been updated in last "release".

**Comment by Art3mK** [comment] 2021-10-11 09:29
v0.10.0 is also missing from helm repo, while it was released 2 weeks ago? @feikesteenbergen, @thedodd could you take a look? 🙏

**Comment by feikesteenbergen** [comment] 2021-12-03 12:59
Oops, something we need to guard against in the linter I suppose. Published 0.8.1, 0.8.2 and 0.10.0 moments ago.

**Comment by agronholm** [comment] 2021-12-03 13:23
Is https://charts.timescale.com not going to be updated going forward?

**Comment by feikesteenbergen** [comment] 2021-12-06 12:09
@agronholm good point, will keep the issue open to ensure this gets addressed.

**Comment by JamesGuthrie** [comment] 2021-12-15 12:25
I opened #324 which is a duplicate of this.

**Comment by TomasVojacek** [comment] 2022-02-08 00:56
> @agronholm good point, will keep the issue open to ensure this gets addressed.

Any update? It has been two months with no changes.

**Comment by paulfantom** [comment] 2022-08-18 10:28
It seems that issue is already fixed and charts are correctly published. If you find that the problem is still happening in your environment, please reopen this ticket.

**Comment by paulfantom** [comment] 2022-08-18 10:29
> Is https://charts.timescale.com/ not going to be updated going forward?

Going forward https://charts.timescale.com is the main and only timescale chart repository.

**Closed by paulfantom** 2022-08-18 10:28 UTC
